name:                icfpc2024
version:             0.1.0.0
github:              "msakai/icfpc2024"
license:             BSD-3-Clause
author:              "Masahiro Sakai"
maintainer:          "masahiro.sakai@gmail.com"
copyright:           "Copyright (c) 2023 Masahiro Sakai"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/msakai/icfpc2024#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- array
- bytestring
- containers
- doctest
- extra
- hspec
- main-tester
- multiset
- process
- random
- recursion-schemes
- time
- unicode-show
- utf8-string
- vector

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  icfpc2024-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - icfpc2024

tests:
  icfpc2024-test:
    main:                spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - icfpc2024

  icfpc2024-doctest:
    main:                doctests.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - icfpc2024
    - doctest